### PR TITLE
Create library and separate example

### PR DESCRIPTION
**Pull request by streeve**
Potential discussion:
- "example" isn't a great name, but I'm not sure how you will differentiate the "standard" solver from sparse etc.
- Unit tests still use the "example" to run different input files
- I removed the `ENABLE_*` flags for simplicity, but it may make sense to keep
- Maybe we should have an official release to match the other proxy apps (and prior to the new work being added)

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by streeve** [comment]
@guangyechen @ricketsonl any suggestions?

**Comment by guangyechen** [comment]
@streeve They look good to me, except that I am not sure about removing the compiler flags under those "ENABLE_GPU". Will the code still compile just fine on CPU/GPU without those flags?

**Comment by streeve** [comment]
> They look good to me, except that I am not sure about removing the compiler flags under those "ENABLE_GPU". Will the code still compile just fine on CPU/GPU without those flags?

As it is now it will use the default enabled Kokkos backend (host or device). If you prefer, we can keep those flags and instead build for the default host or default device backend

**Comment by streeve** [comment]
@guangyechen I added back an option to run on the host, but renamed to `REQUIRE_HOST` since it may already be the default. I prefer this since otherwise we have to go through the list of enabled backends and check whether it's enabled

**Review by guangyechen — COMMENTED** [review]
On the gpu, it still needs something like 
```
cmake -DCMAKE_PREFIX_PATH="$HOME/tmp/Cabana/build/install" -DCMAKE_CXX_COMPILER=$KOKKOS_SRC_DIR/bin/nvcc_wrapper  ..
```

**Comment by streeve** [comment]
> On the gpu, it still needs something like

I forgot that CabanaPIC doesn't have a minimum Cabana version and therefore still supports relatively old Kokkos versions. With new enough Kokkos the `nvcc_wrapper` is automatically used if needed

**Comment by streeve** [comment]
@guangyechen look good?

**Comment by streeve** [comment]
ping @guangyechen

**Pull request merged**
